
CREATE TABLE IF NOT EXISTS "UserTable" (
    "id" BIGINT NOT NULL PRIMARY KEY,
    "experience" INT NOT NULL,
    "refill" TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS WordList (
    id TINYINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS Statistic (
    id BIGINT NOT NULL,
    attempt INT NOT NULL,
    correct INT NOT NULL,
    number INT NOT NULL,
    word_list TINYINT NOT NULL,

    CONSTRAINT pk_statistic PRIMARY KEY (id, word_list, attempt),

    CONSTRAINT fk_word_list_stat
        FOREIGN KEY (word_list)
        REFERENCES WordList(id)
);

CREATE TABLE IF NOT EXISTS Quest (
    entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quest_type TINYINT NOT NULL,
    word_list TINYINT NOT NULL,
    progress TINYINT,
    parameter TINYINT,
    parameter2 TINYINT,
    is_complete BIT NOT NULL,

    CONSTRAINT fk_quest_user
        FOREIGN KEY (user_id)
        REFERENCES "UserTable"("id")
);

CREATE TABLE IF NOT EXISTS Word (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kanji TEXT NOT NULL,
    furigana TEXT NOT NULL,
    english TEXT NOT NULL,
    roman VARCHAR(255) NOT NULL,
    word_list TINYINT NOT NULL,

    CONSTRAINT fk_word_list_words
        FOREIGN KEY (word_list)
        REFERENCES WordList(id)
)

